name: workflow
description: A new Flutter project.
publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  http: ^1.3.0
  flutter_spinkit: ^5.2.0
  lottie: ^3.3.1
  flutter_styled_toast: ^2.2.1
  shared_preferences: ^2.5.3
  percent_indicator: ^4.2.5
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_long.png
    - assets/animations/loading.json
    - assets/animations/first_half.json
    - assets/animations/second_half.json
